[project]
name = "genlm-grammar"
dynamic = ["version"]
description = ""
authors = [
    { name = "The GenLM Team" }
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "frozendict",
    "interegular",
    "lark",
    "numpy",
    "arsenal @ git+https://github.com/timvieira/arsenal.git@master",
    "IPython",
    "graphviz",
    "pandas",
]

[project.optional-dependencies]
bench = [
    "matplotlib",
    "scipy",
    "statsmodels",
]
test = [
    "coverage",
    "pytest",
    "pytest-benchmark",
]

[tool.setuptools.packages.find]
include = ["genlm", "genlm/grammar"]

[[tool.setuptools-rust.ext-modules]]
target = "genlm_earley"
path = "rust/Cargo.toml"
binding = "PyO3"

[build-system]
requires = ["setuptools>=64.0", "setuptools-scm>=8", "setuptools-rust>=1.8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.ruff]
lint.ignore = ["E741", "E743"]
